version: "3.8"
services:
  api:
    container_name: honobackend
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    # environment:
    #   - DATABASE_URL=your_connection_string
    # Add any additional environment variables you need

  web:
    container_name: remixfrontend
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - API_URL=http://localhost:3001
    # add environment variables if needed